spring:

  jpa:
    show_sql: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false
#        default_schema: turns

  liquibase:
    change-log: classpath:eu/giulioquaresima/unicam/turns/liquibase/dbchangelog.xml
    contexts: development
#    default-schema: turns
    drop-first: true
# https://docs.spring.io/spring-security/reference/6.0/servlet/oauth2/resource-server/jwt.html#_specifying_the_authorization_server   
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
          jwk-set-uri: http://localhost:9000/oauth2/jwks # Probabilmente non necessario in quanto dovrebbe autoconfigurarsi tramite issuer-uri