spring:

  jpa:
    show_sql: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false
#        default_schema: turns

  liquibase:
    change-log: classpath:eu/giulioquaresima/unicam/turns/liquibase/dbchangelog.xml
    contexts: development
#    default-schema: turns
    drop-first: true
    
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/baeldung
          jwk-set-uri: http://localhost:8080/auth/realms/baeldung/protocol/openid-connect/certs