-----------------------------------------------------------------
-- Generated by eu.giulioquaresima.unicam.turns.domain.ddl.DDL --
-- at 2022-03-23T20:27:02.977532158Z                           --
-----------------------------------------------------------------

create schema if not exists turns;

    create table turns.owner (
       id int8 generated by default as identity,
        version int8,
        name varchar(255) not null,
        primary key (id)
    );

    create table turns.session (
       id int8 generated by default as identity,
        version int8,
        current_ticket_index int4 not null,
        end_time timestamp,
        maximum_number int4 not null,
        start_time timestamp,
        ticket_dispenser_id int8 not null,
        primary key (id)
    );

    create table turns.session_tickets (
       session_id int8 not null,
        number int4 not null,
        unique_identifier uuid not null,
        withraw_time timestamp not null,
        tickets_order int4 not null,
        primary key (session_id, tickets_order)
    );

    create table turns.ticket_dispenser (
       id int8 generated by default as identity,
        version int8,
        label varchar(255) not null,
        owner_id int8 not null,
        primary key (id)
    );

    alter table if exists turns.session_tickets 
       add constraint UK_f2lu52v9etv714v4sp2pge2bl unique (unique_identifier);

    alter table if exists turns.session 
       add constraint FKm5msfuh6n6c0lbuinymkqf16s 
       foreign key (ticket_dispenser_id) 
       references turns.ticket_dispenser;

    alter table if exists turns.session_tickets 
       add constraint FKbuiqi6yv9vcm70hgsm46mi678 
       foreign key (session_id) 
       references turns.session;

    alter table if exists turns.ticket_dispenser 
       add constraint FKrsixq2cv6d0bjlkcfwkxet2j7 
       foreign key (owner_id) 
       references turns.owner;
