----------------------------------------------------------------
-- Generated by eu.giulioquaresima.unicam.turns.domain.ddl.DDL --
-- at 2022-03-08T23:08:32.384960889Z                          --
----------------------------------------------------------------

    create table session (
       id bigint generated by default as identity,
        version bigint,
        current_ticket_index integer,
        end_time timestamp,
        start_time timestamp,
        ticket_dispenser_id bigint not null,
        primary key (id)
    );

    create table session_tickets (
       session_id bigint not null,
        unique_identifier binary not null,
        withraw_time timestamp not null,
        tickets_order integer not null,
        primary key (session_id, tickets_order)
    );

    create table ticket_dispenser (
       id bigint generated by default as identity,
        version bigint,
        primary key (id)
    );

    alter table session 
       add constraint FKm5msfuh6n6c0lbuinymkqf16s 
       foreign key (ticket_dispenser_id) 
       references ticket_dispenser;

    alter table session_tickets 
       add constraint FKbuiqi6yv9vcm70hgsm46mi678 
       foreign key (session_id) 
       references session;
