-----------------------------------------------------------------
-- Generated by eu.giulioquaresima.unicam.turns.domain.ddl.DDL --
-- at 2022-05-02T20:08:08.026621666Z                           --
-----------------------------------------------------------------

    create table firebase_token (
       id int8 generated by default as identity,
        version int8,
        origin varchar(2048) not null,
        token varchar(255) not null,
        user_id int8 not null,
        primary key (id)
    );

    create table owner (
       id int8 generated by default as identity,
        version int8,
        name varchar(255) not null,
        primary key (id)
    );

    create table session (
       id int8 generated by default as identity,
        version int8,
        current_ticket_index int4 not null,
        end_time timestamp,
        maximum_number int4 not null,
        start_time timestamp,
        ticket_dispenser_id int8 not null,
        primary key (id)
    );

    create table ticket (
       id int8 generated by default as identity,
        version int8,
        cancelled boolean not null,
        number int4 not null,
        unique_identifier uuid not null,
        withdraw_time timestamp not null,
        owner_id int8,
        session_id int8 not null,
        tickets_order int4,
        primary key (id)
    );

    create table ticket_dispenser (
       id int8 generated by default as identity,
        version int8,
        label varchar(255) not null,
        zone_id varchar(255) not null,
        owner_id int8 not null,
        primary key (id)
    );

    create table you_sir (
       id int8 generated by default as identity,
        version int8,
        username varchar(255) not null,
        primary key (id)
    );

    create table you_sir_owners (
       user_id int8 not null,
        owners_id int8 not null,
        primary key (user_id, owners_id)
    );

    alter table if exists firebase_token 
       add constraint UK_g12k4gbr9957c908vhrmvqjpm unique (token);

    alter table if exists ticket 
       add constraint UK_pi1jdbssw2n1pjcnd4fdb7w9q unique (unique_identifier);

    alter table if exists you_sir 
       add constraint UK_oprv7pq4d8j9wifyk0ipk43r5 unique (username);

    alter table if exists firebase_token 
       add constraint FK52cb3reml39179ilckuhgvehq 
       foreign key (user_id) 
       references you_sir;

    alter table if exists session 
       add constraint FKm5msfuh6n6c0lbuinymkqf16s 
       foreign key (ticket_dispenser_id) 
       references ticket_dispenser;

    alter table if exists ticket 
       add constraint FKm0q6isjwcx58c7upndontlwfq 
       foreign key (owner_id) 
       references you_sir;

    alter table if exists ticket 
       add constraint FK5x0dvk4itqbdpu2dxdo02b5f7 
       foreign key (session_id) 
       references session;

    alter table if exists ticket_dispenser 
       add constraint FKrsixq2cv6d0bjlkcfwkxet2j7 
       foreign key (owner_id) 
       references owner;

    alter table if exists you_sir_owners 
       add constraint FKjnl0gr03iod6ulwunuaujn2up 
       foreign key (owners_id) 
       references owner;

    alter table if exists you_sir_owners 
       add constraint FKnam1xakq35vxqf1ps1vm1famm 
       foreign key (user_id) 
       references you_sir;
