-----------------------------------------------------------------
-- Generated by eu.giulioquaresima.unicam.turns.domain.ddl.DDL --
-- at 2022-05-02T20:07:42.390523237Z                           --
-----------------------------------------------------------------

    create table firebase_token (
       id bigint generated by default as identity,
        version bigint,
        token varchar(255) not null,
        user_id bigint not null,
        primary key (id)
    );

    create table owner (
       id bigint generated by default as identity,
        version bigint,
        name varchar(255) not null,
        primary key (id)
    );

    create table session (
       id bigint generated by default as identity,
        version bigint,
        current_ticket_index integer not null,
        end_time timestamp,
        maximum_number integer not null,
        start_time timestamp,
        ticket_dispenser_id bigint not null,
        primary key (id)
    );

    create table ticket (
       id bigint generated by default as identity,
        version bigint,
        cancelled boolean not null,
        number integer not null,
        unique_identifier binary not null,
        withdraw_time timestamp not null,
        owner_id bigint,
        session_id bigint not null,
        tickets_order integer,
        primary key (id)
    );

    create table ticket_dispenser (
       id bigint generated by default as identity,
        version bigint,
        label varchar(255) not null,
        zone_id varchar(255) not null,
        owner_id bigint not null,
        primary key (id)
    );

    create table you_sir (
       id bigint generated by default as identity,
        version bigint,
        username varchar(255) not null,
        primary key (id)
    );

    create table you_sir_owners (
       user_id bigint not null,
        owners_id bigint not null,
        primary key (user_id, owners_id)
    );

    alter table firebase_token 
       add constraint UK_g12k4gbr9957c908vhrmvqjpm unique (token);

    alter table ticket 
       add constraint UK_pi1jdbssw2n1pjcnd4fdb7w9q unique (unique_identifier);

    alter table you_sir 
       add constraint UK_oprv7pq4d8j9wifyk0ipk43r5 unique (username);

    alter table firebase_token 
       add constraint FK52cb3reml39179ilckuhgvehq 
       foreign key (user_id) 
       references you_sir;

    alter table session 
       add constraint FKm5msfuh6n6c0lbuinymkqf16s 
       foreign key (ticket_dispenser_id) 
       references ticket_dispenser;

    alter table ticket 
       add constraint FKm0q6isjwcx58c7upndontlwfq 
       foreign key (owner_id) 
       references you_sir;

    alter table ticket 
       add constraint FK5x0dvk4itqbdpu2dxdo02b5f7 
       foreign key (session_id) 
       references session;

    alter table ticket_dispenser 
       add constraint FKrsixq2cv6d0bjlkcfwkxet2j7 
       foreign key (owner_id) 
       references owner;

    alter table you_sir_owners 
       add constraint FKjnl0gr03iod6ulwunuaujn2up 
       foreign key (owners_id) 
       references owner;

    alter table you_sir_owners 
       add constraint FKnam1xakq35vxqf1ps1vm1famm 
       foreign key (user_id) 
       references you_sir;
