----------------------------------------------------------------
-- Generated by eu.giulioquaresima.unicam.turns.domain.ddl.DDL --
-- at 2021-12-17T03:44:45.561511813Z                          --
----------------------------------------------------------------

    create table location (
       id bigint generated by default as identity,
        version timestamp,
        name varchar(255),
        zone_id varchar(255),
        tenant_id bigint,
        primary key (id)
    );

    create table service (
       id bigint generated by default as identity,
        version timestamp,
        name varchar(255),
        location_id bigint,
        session_scheduler_id bigint,
        primary key (id)
    );

    create table service_reception (
       id bigint generated by default as identity,
        version timestamp,
        label varchar(255),
        service_id bigint,
        primary key (id)
    );

    create table session (
       id bigint generated by default as identity,
        version timestamp,
        end_time timestamp,
        label varchar(255),
        start_time timestamp,
        last_drawn_ticket_id bigint,
        last_withdrawn_ticket_id bigint,
        service_id bigint,
        session_configuration_id bigint,
        primary key (id)
    );

    create table session_ticket_numbers (
       session_id bigint not null,
        ticket_numbers varchar(8),
        ticket_numbers_order integer not null,
        primary key (session_id, ticket_numbers_order)
    );

    create table session_configuration (
       id bigint generated by default as identity,
        version timestamp,
        bijective_numeration_digits varchar(255),
        postpone_enabled boolean not null,
        scramble_tickets boolean not null,
        use_bijective_numeration boolean not null,
        primary key (id)
    );

    create table session_scheduling (
       id bigint generated by default as identity,
        version timestamp,
        primary key (id)
    );

    create table session_scheduling_default_shifts (
       session_scheduling_id bigint not null,
        day_of_week integer,
        duration bigint,
        name varchar(255) not null,
        reset_ticket_source boolean not null,
        start_time time
    );

    create table tenant (
       id bigint generated by default as identity,
        version timestamp,
        name varchar(255),
        primary key (id)
    );

    create table ticket (
       id bigint generated by default as identity,
        version timestamp,
        draw_time timestamp,
        number varchar(8) not null,
        withdraw_time timestamp,
        assigned_reception_id bigint,
        previous_id bigint,
        service_reception_id bigint,
        session_id bigint not null,
        user_id bigint,
        primary key (id)
    );

    create table user (
       id bigint generated by default as identity,
        version timestamp,
        family_name varchar(255),
        given_name varchar(255),
        prefix varchar(255),
        suffix varchar(255),
        title varchar(255),
        primary key (id)
    );

    alter table location 
       add constraint FKnn6oi51wywywpykyqbr9aqb87 
       foreign key (tenant_id) 
       references tenant;

    alter table service 
       add constraint FKa72hqlm2hy63lgmvjqhen5imv 
       foreign key (location_id) 
       references location;

    alter table service 
       add constraint FKjsfctm8bdd5nsdbeharam5q9b 
       foreign key (session_scheduler_id) 
       references session_scheduling;

    alter table service_reception 
       add constraint FK2sjp0wg8r62igo3u7lsnya2xl 
       foreign key (service_id) 
       references service;

    alter table session 
       add constraint FKo11h2pg43i71ttltxnoa8vo41 
       foreign key (last_drawn_ticket_id) 
       references ticket;

    alter table session 
       add constraint FKc73ttpiq7niv09qw653o7ihkc 
       foreign key (last_withdrawn_ticket_id) 
       references ticket;

    alter table session 
       add constraint FK1e2ielct2ao0py0db1j7st816 
       foreign key (service_id) 
       references service;

    alter table session 
       add constraint FK8diyibcgrnvsayxfygcq74we4 
       foreign key (session_configuration_id) 
       references session_configuration;

    alter table session_ticket_numbers 
       add constraint FKll4bpgu6aj0g69lqg0n81ov5l 
       foreign key (session_id) 
       references session;

    alter table session_scheduling_default_shifts 
       add constraint FKpdkye21o2hsxjkhcupi1habwx 
       foreign key (session_scheduling_id) 
       references session_scheduling;

    alter table ticket 
       add constraint FKdl16nr6spjqmnov5i91f6kxdm 
       foreign key (assigned_reception_id) 
       references service_reception;

    alter table ticket 
       add constraint FKt8lcbae89ok0cbh6ulp7xr5rd 
       foreign key (previous_id) 
       references ticket;

    alter table ticket 
       add constraint FKmob5fn4nw0022qhph1kak2576 
       foreign key (service_reception_id) 
       references service_reception;

    alter table ticket 
       add constraint FK5x0dvk4itqbdpu2dxdo02b5f7 
       foreign key (session_id) 
       references session;

    alter table ticket 
       add constraint FKdvt57mcco3ogsosi97odw563o 
       foreign key (user_id) 
       references user;
