----------------------------------------------------------------
-- Generated by eu.giulioquaresima.unicam.turns.domain.ddl.DDL --
-- at 2021-12-08T20:52:45.807798249Z                          --
----------------------------------------------------------------

    create table location (
       id int8 generated by default as identity,
        tenant_id int8,
        primary key (id)
    );

    create table service (
       id int8 generated by default as identity,
        location_id int8,
        session_scheduler_id int8,
        primary key (id)
    );

    create table service_reception (
       id int8 generated by default as identity,
        service_id int8,
        primary key (id)
    );

    create table session (
       id int8 generated by default as identity,
        end_time timestamp,
        name varchar(255),
        start_time timestamp,
        ticket_source_id int8,
        primary key (id)
    );

    create table session_configuration (
       id int8 generated by default as identity,
        primary key (id)
    );

    create table session_scheduling (
       id int8 generated by default as identity,
        primary key (id)
    );

    create table session_scheduling_default_shifts (
       session_scheduling_id int8 not null,
        day_of_week int4,
        duration int8,
        name varchar(255) not null,
        reset_ticket_source boolean not null,
        start_time time
    );

    create table tenant (
       id int8 generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table ticket (
       id int8 generated by default as identity,
        label varchar(8),
        seq int4 not null,
        service_reception_id int8,
        session_id int8 not null,
        user_id int8,
        primary key (id)
    );

    create table ticket_source (
       id int8 generated by default as identity,
        service_id int8,
        ticket_source_configuration_id int8,
        primary key (id)
    );

    create table ticket_source_configuration (
       id int8 generated by default as identity,
        digits varchar(255),
        minimum_ticket_label_length int4 not null,
        postpone_enabled boolean not null,
        primary key (id)
    );

    create table user (
       id int8 generated by default as identity,
        primary key (id)
    );

    alter table if exists location 
       add constraint FKnn6oi51wywywpykyqbr9aqb87 
       foreign key (tenant_id) 
       references tenant;

    alter table if exists service 
       add constraint FKa72hqlm2hy63lgmvjqhen5imv 
       foreign key (location_id) 
       references location;

    alter table if exists service 
       add constraint FKjsfctm8bdd5nsdbeharam5q9b 
       foreign key (session_scheduler_id) 
       references session_scheduling;

    alter table if exists service_reception 
       add constraint FK2sjp0wg8r62igo3u7lsnya2xl 
       foreign key (service_id) 
       references service;

    alter table if exists session 
       add constraint FK5od48nmiagthv6dw8x7wiqwn5 
       foreign key (ticket_source_id) 
       references ticket_source;

    alter table if exists session_scheduling_default_shifts 
       add constraint FKpdkye21o2hsxjkhcupi1habwx 
       foreign key (session_scheduling_id) 
       references session_scheduling;

    alter table if exists ticket 
       add constraint FKmob5fn4nw0022qhph1kak2576 
       foreign key (service_reception_id) 
       references service_reception;

    alter table if exists ticket 
       add constraint FK5x0dvk4itqbdpu2dxdo02b5f7 
       foreign key (session_id) 
       references session;

    alter table if exists ticket 
       add constraint FKdvt57mcco3ogsosi97odw563o 
       foreign key (user_id) 
       references user;

    alter table if exists ticket_source 
       add constraint FKaxjf00j1ykoocar95jif184fk 
       foreign key (service_id) 
       references service;

    alter table if exists ticket_source 
       add constraint FKddpiblmdr0xa8tsi6g17gycp2 
       foreign key (ticket_source_configuration_id) 
       references ticket_source_configuration;
