----------------------------------------------------------------
-- Generated by eu.giulioquaresima.unicam.turns.domain.ddl.DDL --
-- at 2021-12-04T16:31:05.986563253Z                          --
----------------------------------------------------------------

    create table location (
       id int8 generated by default as identity,
        tenant_id int8,
        primary key (id)
    );

    create table session (
       id int8 generated by default as identity,
        location_id int8,
        primary key (id)
    );

    create table tenant (
       id int8 generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table ticket (
       id int8 generated by default as identity,
        session_id int8,
        primary key (id)
    );

    alter table if exists location 
       add constraint FKnn6oi51wywywpykyqbr9aqb87 
       foreign key (tenant_id) 
       references tenant;

    alter table if exists session 
       add constraint FKk9sxbgtd06ugbbullt82vbxmq 
       foreign key (location_id) 
       references location;

    alter table if exists ticket 
       add constraint FK5x0dvk4itqbdpu2dxdo02b5f7 
       foreign key (session_id) 
       references session;
